name: Your New Jekyll Site
markdown: redcarpet
#pygments: true
pygments: false
future: true
destination: RELEASE
source: site
permalink: /blog/:year/:day_:month_:title/
TZ: Europe/London
encoding: ASCII-8BIT
