name: The New Event Handler site
pygments: false
future: false
destination: RELEASE
source: site
permalink: /blog/:year/:day_:month_:title/
TZ: Europe/London
encoding: ASCII-8BIT

markdown:      redcarpet
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile